function y = notch46hz(x)
%NOTCH46HZ Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 14-Dec-2016 14:43:25

persistent Hd;

if isempty(Hd)
    
    N  = 6;        % Order
    F0 = 46.9375;  % Center frequency
    Q  = 2.5;      % Q-factor
    Fs = 250;      % Sampling Frequency
    
    h = fdesign.notch('N,F0,Q', N, F0, Q, Fs);
    
    Hd = design(h, 'butter', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


